name: Build Debug APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Verify APK was built
        run: |
          ls app/build/outputs/apk/debug/app-debug.apk || (echo "APK not found!" && exit 1)

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: PocketPool-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag debug-${{ github.sha }}
          git push origin debug-${{ github.sha }}

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: "Debug Build - ${{ github.sha }}"
          tag_name: "debug-${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
